'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { Clock, BarChart2, Copy, Check, Zap, Film } from 'lucide-react'

interface Video {
  id: string
  title: string
  publishedAt: string
  views: number
  likes: number
  comments: number
  duration: string
}

interface Props {
  videos: Video[]
  channelName: string
}

function durationSeconds(iso: string): number {
  const m = iso?.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/)
  if (!m) return 0
  return (parseInt(m[1] || '0') * 3600) + (parseInt(m[2] || '0') * 60) + parseInt(m[3] || '0')
}

function isShort(v: Video) { return durationSeconds(v.duration) <= 60 }

function fmt(n: number) {
  if (n >= 1_000_000_000) return (n / 1_000_000_000).toFixed(1) + 'B'
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(1) + 'M'
  if (n >= 1_000) return (n / 1_000).toFixed(1) + 'K'
  return n.toString()
}

const DAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
const HOURS = ['12am','1am','2am','3am','4am','5am','6am','7am','8am','9am','10am','11am',
               '12pm','1pm','2pm','3pm','4pm','5pm','6pm','7pm','8pm','9pm','10pm','11pm']

export default function InsightsBar({ videos, channelName }: Props) {
  const [copied, setCopied] = useState(false)

  // Best posting day + hour
  const dayScores: Record<number, { views: number; count: number }> = {}
  const hourScores: Record<number, { views: number; count: number }> = {}

  videos.forEach(v => {
    const d = new Date(v.publishedAt)
    const day = d.getDay()
    const hour = d.getHours()
    if (!dayScores[day]) dayScores[day] = { views: 0, count: 0 }
    if (!hourScores[hour]) hourScores[hour] = { views: 0, count: 0 }
    dayScores[day].views += v.views
    dayScores[day].count++
    hourScores[hour].views += v.views
    hourScores[hour].count++
  })

  const bestDay = Object.entries(dayScores)
    .map(([day, s]) => ({ day: parseInt(day), avg: s.views / s.count }))
    .sort((a, b) => b.avg - a.avg)[0]

  const bestHour = Object.entries(hourScores)
    .map(([hour, s]) => ({ hour: parseInt(hour), avg: s.views / s.count }))
    .sort((a, b) => b.avg - a.avg)[0]

  // Shorts vs Videos
  const shorts = videos.filter(isShort)
  const regularVideos = videos.filter(v => !isShort(v))
  const avgShortViews = shorts.length ? Math.round(shorts.reduce((s, v) => s + v.views, 0) / shorts.length) : 0
  const avgVideoViews = regularVideos.length ? Math.round(regularVideos.reduce((s, v) => s + v.views, 0) / regularVideos.length) : 0
  const shortsWin = avgShortViews > avgVideoViews

  // Top video
  const topVideo = [...videos].sort((a, b) => b.views - a.views)[0]
  const totalViews = videos.reduce((s, v) => s + v.views, 0)
  const avgEngagement = videos.length
    ? ((videos.reduce((s, v) => s + v.likes + v.comments, 0) / videos.reduce((s, v) => s + v.views, 0)) * 100).toFixed(2)
    : '0'

  // Copy report
  const handleCopy = () => {
    const report = `VidMetrics Report — ${channelName}
Generated: ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}

📊 OVERVIEW
• Total videos analyzed: ${videos.length}
• Total views: ${fmt(totalViews)}
• Avg engagement rate: ${avgEngagement}%

🏆 TOP VIDEO
"${topVideo?.title}" — ${fmt(topVideo?.views)} views

🕐 BEST TIME TO POST
• Best day: ${bestDay ? DAYS[bestDay.day] : 'N/A'} (avg ${bestDay ? fmt(Math.round(bestDay.avg)) : 0} views)
• Best hour: ${bestHour ? HOURS[bestHour.hour] : 'N/A'} (avg ${bestHour ? fmt(Math.round(bestHour.avg)) : 0} views)

⚡ SHORTS vs VIDEOS
• Shorts (${shorts.length}): avg ${fmt(avgShortViews)} views
• Videos (${regularVideos.length}): avg ${fmt(avgVideoViews)} views
• ${shortsWin ? 'Shorts outperform regular videos' : 'Regular videos outperform Shorts'}

— Generated by VidMetrics`

    navigator.clipboard.writeText(report)
    setCopied(true)
    setTimeout(() => setCopied(false), 2500)
  }

  return (
    <>
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35, delay: 0.15 }}
      style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12 }}
      className="insights-grid"
    >
      {/* Best posting time */}
      <div style={{
        background: '#111118', border: '1px solid rgba(255,255,255,0.05)',
        borderRadius: 14, padding: 20,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
          <div style={{
            width: 32, height: 32, borderRadius: 8,
            background: 'rgba(96,165,250,0.1)', border: '1px solid rgba(96,165,250,0.2)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <Clock size={14} color="#60A5FA" />
          </div>
          <p style={{ color: '#9CA3AF', fontSize: 12, fontWeight: 600, letterSpacing: '0.04em', textTransform: 'uppercase' }}>
            Best time to post
          </p>
        </div>
        {bestDay && bestHour ? (
          <>
            <p style={{ color: '#fff', fontSize: 22, fontWeight: 800, letterSpacing: '-0.02em', lineHeight: 1 }}>
              {DAYS[bestDay.day]}
            </p>
            <p style={{ color: '#60A5FA', fontSize: 14, fontWeight: 600, marginTop: 4 }}>
              around {HOURS[bestHour.hour]}
            </p>
            <p style={{ color: '#4B5563', fontSize: 11, marginTop: 8 }}>
              Based on top-performing upload times
            </p>
          </>
        ) : (
          <p style={{ color: '#4B5563', fontSize: 13 }}>Not enough data</p>
        )}
      </div>

      {/* Shorts vs Videos */}
      <div style={{
        background: '#111118', border: '1px solid rgba(255,255,255,0.05)',
        borderRadius: 14, padding: 20,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
          <div style={{
            width: 32, height: 32, borderRadius: 8,
            background: 'rgba(167,139,250,0.1)', border: '1px solid rgba(167,139,250,0.2)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <BarChart2 size={14} color="#A78BFA" />
          </div>
          <p style={{ color: '#9CA3AF', fontSize: 12, fontWeight: 600, letterSpacing: '0.04em', textTransform: 'uppercase' }}>
            Shorts vs videos
          </p>
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {/* Shorts bar */}
          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
                <Zap size={11} color="#FF6B9D" />
                <span style={{ color: '#9CA3AF', fontSize: 12 }}>Shorts ({shorts.length})</span>
              </div>
              <span style={{ color: shortsWin ? '#FF6B9D' : '#6B7280', fontSize: 12, fontWeight: 600 }}>
                {fmt(avgShortViews)} avg
              </span>
            </div>
            <div style={{ height: 5, background: '#1E1E2E', borderRadius: 99 }}>
              <div style={{
                height: '100%', borderRadius: 99,
                background: 'linear-gradient(90deg,#FF0040,#FF6B9D)',
                width: `${Math.min(100, (avgShortViews / Math.max(avgShortViews, avgVideoViews)) * 100)}%`,
                transition: 'width 0.6s ease',
              }} />
            </div>
          </div>
          {/* Videos bar */}
          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
                <Film size={11} color="#60A5FA" />
                <span style={{ color: '#9CA3AF', fontSize: 12 }}>Videos ({regularVideos.length})</span>
              </div>
              <span style={{ color: !shortsWin ? '#60A5FA' : '#6B7280', fontSize: 12, fontWeight: 600 }}>
                {fmt(avgVideoViews)} avg
              </span>
            </div>
            <div style={{ height: 5, background: '#1E1E2E', borderRadius: 99 }}>
              <div style={{
                height: '100%', borderRadius: 99,
                background: 'linear-gradient(90deg,#3B82F6,#60A5FA)',
                width: `${Math.min(100, (avgVideoViews / Math.max(avgShortViews, avgVideoViews)) * 100)}%`,
                transition: 'width 0.6s ease',
              }} />
            </div>
          </div>
        </div>
        <p style={{ color: '#4B5563', fontSize: 11, marginTop: 10 }}>
          {shortsWin ? '⚡ Shorts drive more views per post' : '🎬 Long-form content wins here'}
        </p>
      </div>

      {/* Copy report */}
      <div style={{
        background: '#111118', border: '1px solid rgba(255,255,255,0.05)',
        borderRadius: 14, padding: 20,
        display: 'flex', flexDirection: 'column', justifyContent: 'space-between',
      }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
            <div style={{
              width: 32, height: 32, borderRadius: 8,
              background: 'rgba(52,211,153,0.1)', border: '1px solid rgba(52,211,153,0.2)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              {copied ? <Check size={14} color="#34D399" /> : <Copy size={14} color="#34D399" />}
            </div>
            <p style={{ color: '#9CA3AF', fontSize: 12, fontWeight: 600, letterSpacing: '0.04em', textTransform: 'uppercase' }}>
              Channel report
            </p>
          </div>
          <p style={{ color: '#fff', fontSize: 15, fontWeight: 700, lineHeight: 1.3, marginBottom: 6 }}>
            {channelName}
          </p>
          <p style={{ color: '#4B5563', fontSize: 12, lineHeight: 1.5 }}>
            {videos.length} videos · {fmt(totalViews)} total views · {avgEngagement}% avg engagement
          </p>
        </div>
        <button
          onClick={handleCopy}
          style={{
            marginTop: 16,
            display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
            background: copied ? 'rgba(52,211,153,0.1)' : 'rgba(255,255,255,0.06)',
            border: `1px solid ${copied ? 'rgba(52,211,153,0.3)' : 'rgba(255,255,255,0.1)'}`,
            color: copied ? '#34D399' : '#9CA3AF',
            borderRadius: 10, padding: '9px 16px',
            fontSize: 13, fontWeight: 500, cursor: 'pointer',
            transition: 'all 200ms ease',
          }}
          onMouseEnter={e => {
            if (!copied) {
              (e.currentTarget as HTMLElement).style.background = 'rgba(255,255,255,0.1)'
              ;(e.currentTarget as HTMLElement).style.color = '#fff'
            }
          }}
          onMouseLeave={e => {
            if (!copied) {
              (e.currentTarget as HTMLElement).style.background = 'rgba(255,255,255,0.06)'
              ;(e.currentTarget as HTMLElement).style.color = '#9CA3AF'
            }
          }}
        >
          {copied ? <Check size={13} /> : <Copy size={13} />}
          {copied ? 'Copied to clipboard!' : 'Copy report'}
        </button>
      </div>
    </motion.div>
    <style>{`
      @media (max-width: 640px) {
        .insights-grid { grid-template-columns: 1fr !important; }
      }
    `}</style>
    </>
  )
}
